# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Pawel Niewiadomski
tagline: ''
description: 'A few observations on world of software development, life and all the things.'

author:
  name: Pawel Niewiadomski
  url: https://twitter.com/devonsteroids
  email: 11110000b@gmail.com
  github:	pawelniewie
  twitter: devonsteroids
  linkedin: pawelniewiadomski

pagination:
  limit: 10
  title_suffix: " (:num)"

# Custom vars
version: 2.0.0

baseurl: ""
url: https://pawelniewiadomski.com

fb_admins: http://facebook.com/pawelniewie
locale:	en_US
avatar:	/media/avatar.jpg

feed:
  path: atom.xml

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-srcset
- jekyll-feed
- octopress-paginate
- jekyll-gist
- jekyll/tagging
- jekyll-tagging-related_posts
exclude:
- Gemfile
- Gemfile.lock
- wercker.yml
