# Site settings
title: Pawel Niewiadomski
email: 11110000b@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A few observations on world of software development, life and all the things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pawelniewiadomski.com" # the base hostname & protocol for your site
twitter_username: devonsteroids
github_username:  pawelniewie

# Build settings
markdown: kramdown
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap