# Site settings
# http://www.maxmasnick.com/2012/01/21/jekyll_s3_cloudfront/
title: Pawel Niewiadomski
email: 11110000b@gmail.com
paginate: 1
description: > # this means to ignore newlines until "baseurl:"
  A few observations on world of software development, life and all the things.
baseurl: /
url: "http://pawelniewiadomski.com" # the base hostname & protocol for your site
twitter_username: devonsteroids
github_username:  pawelniewie
# Build settings
markdown: kramdown
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- wercker.yml