# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pawel Niewiadomski
tagline:          ''
description:      'A few observations on world of software development, life and all the things.'

author:
  name:           'Pawel Niewiadomski'
  url:            https://twitter.com/devonsteroids
  email:			11110000b@gmail.com
  github:	pawelniewie
  twitter: devonsteroids

paginate:         5

# Custom vars
version:          2.0.0

baseurl: ""
url: "http://pawelniewiadomski.com"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- wercker.yml