source 'https://rubygems.org'
ruby '2.3.3'

gem 'jekyll'
gem 'jekyll-mentions', '>=0.2.1'
gem 'jemoji'
gem 'html-pipeline'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-srcset', github: 'pawelniewie/jekyll-srcset', branch: 'feature/site-url-in-img-tag'
gem 'jekyll-feed'
gem 'octopress-hooks', github: 'octopress/hooks'
gem 'octopress-paginate', github: 'octopress/paginate'
gem 'redcarpet'
gem 'pygments.rb'
gem 'jekyll-gist'
gem 'jekyll-tagging-related_posts'